FROM node:16

ENV MONGODB_CONNECTION_PROTOCOL mongodb+srv
ENV MONGODB_DB_NAME gha-demo1
ENV MONGODB_CLUSTER_ADDRESS cluster0.x4bg7vr.mongodb.net
ENV MONGODB_USERNAME haseeb57
ENV MONGODB_PASSWORD SDRLnk9SeOEe7IMK

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

CMD ["npm", "start"]